name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install and run
        run: |
          export TZ="Europe/Tallinn"
          npm install -g nyc
          node --allow-natives-syntax -r ./test.js test/index.js --tap
          nyc node --allow-natives-syntax -r ./test.js test/index.js --no-status
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

